require 'hoe'
require './lib/fbup/version.rb'


Hoe.spec 'fbup' do
  self.version = SportDb::Module::Fbup::VERSION

  self.summary = "fbup - (auto-)update machinery for footbal match schedules & more in football.txt; incl. (auto-sync & commit) support for github openfootball repos & more"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
       ['gitti',              '>= 0.6.1'],
       ['sportdb-writers',    '>= 0.4.1'],
       ['leagues',            '>= 0.1.1'],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end
