require 'hoe'
require './lib/openfootball/version.rb'


Hoe.spec 'openfootball' do
  self.version = Openfootball::VERSION

  self.summary = "openfootball - config settings for openfootball repos @ github; incl. mapping of league codes to repos and directory style and custom basename and more"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
       ['gitti'],
       ['cocos'],
       ['season-formats'],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end
